### ISSUE TITLE
Make the server monitor more pretty

### ISSUE THREAD

**Issue by yogwoggf** [TAServers/issues#2]
So, when I was experimenting with both Chromium and Awesomium, I'm _99%_ sure that you can set the `body` CSS to transparent, and it will carry over to GMod.

Maybe you could carry over the transparency to the material?
![example](https://i.imgur.com/rOHYE0H.png)
The sudden cutoff is jarring, and it'd look much nicer if the background was transparent or the background would be a rounded rectangle.

**Comment by Zubbbz** [comment]
dumb issue, don't make an issue to fix something that isn't broken and the solution is subjective
