### ISSUE TITLE
Fading Doors replacement

### ISSUE THREAD

**Issue by Zubbbz** [TAServers/issues#4]
Most of the work is already done [here](https://gist.github.com/Zubbbz/7958eefd79fab1f6a2fc795ae23ff68b)

**Comment by dustinandrew412** [comment]
Hi there! If you're looking for a quick replacement for your Chester fading doors, you might want to check with a local home improvement store or contractor who specializes in doors. You can also search online for suppliers who offer [Chester quick replacement](https://garagedoorrepairchester.com/garage-door-replacement/) doors specifically designed to replace fading doors. Another option is to check with the manufacturer of your current doors to see if they have replacement parts or suggestions for a quick fix. Hope this helps!

**Comment by Zubbbz** [comment]
What the fuck
