### ISSUE TITLE
[Minecraft Mod]: Discord Integration

### ISSUE THREAD

**Issue by thermospud** [TAServers/issues#42]
### Modrinth Link

https://modrinth.com/plugin/dcintegration/versions?l=fabric&g=1.20.1

### Mod Type(s)

Social

### Supports 1.20.1 Fabric

- [X] Yes

### Details

Discord relay to act as a replacement until Derpius makes it or something

**Comment by Derpius** [comment]
https://discord.com/channels/800234484649820163/1131301276529995979/1221175665806540961

**Comment by thermospud** [comment]
couldve suggested a alternative but i can just make a separate issue i suppose

**Comment by Derpius** [comment]
Can also edit the issue (FYI switching the close reason for the triage workflow)
