### ISSUE TITLE
[Minecraft Mod]: Iron Chests Restocked

### ISSUE THREAD

**Issue by Xandertron** [TAServers/issues#43]
### Modrinth Link

https://modrinth.com/mod/ironchests

### Mod Type(s)

Storage

### Supports 1.20.1 Fabric

- [X] Yes

### Details

adds bigger chests, would work well with tom's storage

**Comment by thermospud** [comment]
theres also this which is less popular but doesn't have the useless key/lock mechanic https://modrinth.com/mod/reinforced-chests

**Comment by thermospud** [comment]
not sure why i didn't see this issue earlier when i commented on the tom's storage issue

**Comment by Derpius** [comment]
I much prefer the reinforced chests mod cause it doesn't add stupid shit like dirt chests

**Comment by Derpius** [comment]
Reinforced chests have been added for less bloat while providing the same core functionality, so counting this as completed
