### ISSUE TITLE
backpacks

### ISSUE THREAD

**Issue by Devioussie** [TAServers/issues#45]
### Modrinth Link

https://modrinth.com/mod/packed-up-backpacks

### Mod Type(s)

Equipment, Storage, Utility

### Supports 1.20.1 Fabric

- [X] Yes

**Comment by Derpius** [comment]
Closing as duplicate of #55 

Mods that serve the same function can be combined into a single issue. This way we can discuss the concept of on-player storage enhancements vs. two different implementations of the same thing
