### ISSUE TITLE
[Minecraft Mod]: /home

### ISSUE THREAD

**Issue by yousifhub** [TAServers/issues#46]
### Modrinth Link

https://www.curseforge.com/minecraft/mc-mods/set-home-waypoints

### Mod Type(s)

Utility

### Supports 1.20.1 Fabric

- [X] Yes

### Details

A mod that /sethome and /home to tp to that /home

**Comment by Derpius** [comment]
Outmodes existing stasis chamber system created on the server, and makes trains less useful

Discussed here: https://discord.com/channels/800234484649820163/800460584687501312/1249115230311813251
