### ISSUE TITLE
[Minecraft Mod]: Minimap Xaero's

### ISSUE THREAD

**Issue by yousifhub** [TAServers/issues#47]
### Modrinth Link

https://www.curseforge.com/minecraft/mc-mods/xaeros-minimap

### Mod Type(s)

Utility

### Supports 1.20.1 Fabric

- [X] Yes

### Details

Probably can be downloaded as extra mod but nice to have it pre downloaded with the pack

**Comment by Derpius** [comment]
Adding in the new pack version
