### ISSUE TITLE
[Minecraft Mod]: Jade mod (What am i looking at)

### ISSUE THREAD

**Issue by yousifhub** [TAServers/issues#48]
### Modrinth Link

https://www.curseforge.com/minecraft/mc-mods/jade

### Mod Type(s)

Utility

### Supports 1.20.1 Fabric

- [X] Yes

### Details

Nice to have

**Comment by Derpius** [comment]
Adding in the upcoming pack version. Also please use Modrinth links (the pack is on modrinth, so it populates dependencies and metadata correctly)
