### ISSUE TITLE
[Minecraft Mod]: Leaves be gone + Ultimine

### ISSUE THREAD

**Issue by yousifhub** [TAServers/issues#50]
### Modrinth Link

https://www.curseforge.com/minecraft/mc-mods/leaves-be-gone ; https://www.curseforge.com/minecraft/mc-mods/ftb-ultimine-fabric

### Mod Type(s)

Optimisation

### Supports 1.20.1 Fabric

- [X] Yes

### Details

Both together can help with tree harvesting

**Comment by Derpius** [comment]
Added leaves be gone as it's purely QoL

Ultimine/veinminer etc. is more controversial (reduces the need to use other mods for mining). Feel free to raise that as a separate request so it can be tracked independently
