### ISSUE TITLE
[Minecraft Mod]: WATUT

### ISSUE THREAD

**Issue by yousifhub** [TAServers/issues#54]
### Modrinth Link

https://www.curseforge.com/minecraft/mc-mods/what-are-they-up-to

### Mod Type(s)

Social

### Supports 1.20.1 Fabric

- [X] Yes

### Details

To see what are they doing :)

**Comment by yousifhub** [comment]
this is good to add aside the Simple Voice Chat

**Comment by Derpius** [comment]
Adding in the new pack version
