### ISSUE TITLE
[Minecraft Mod]: Vivecraft (VR MC)

### ISSUE THREAD

**Issue by yousifhub** [TAServers/issues#56]
### Modrinth Link

https://www.vivecraft.org/

### Mod Type(s)

Other

### Supports 1.20.1 Fabric

- [X] Yes

### Details

For VR experiance if we wanna see them move in VR it needs to be downloaded by all

**Comment by Derpius** [comment]
Added in the latest pack (we'll see if it conflicts with distant horizons in non-vr mode)
