### ISSUE TITLE
[Minecraft Mod]: Better Recipe Books

### ISSUE THREAD

**Issue by yousifhub** [TAServers/issues#57]
### Modrinth Link

https://www.curseforge.com/minecraft/mc-mods/brb

### Mod Type(s)

Utility

### Supports 1.20.1 Fabric

- [X] Yes

### Details

Adds recipe books to brewing stands

**Comment by Derpius** [comment]
Isn't this outmoded by JEI and its extensions?

Also, this was literally causing crashes when you installed it locally on your end, so closing
