### ISSUE TITLE
[Minecraft Mod]: Create: Estrogen

### ISSUE THREAD

**Issue by ELPatitoLoco** [TAServers/issues#58]
### Modrinth Link

https://modrinth.com/mod/estrogen

### Mod Type(s)

Technology

### Supports 1.20.1 Fabric

- [X] Yes

### Details

Simple Create addon that allows the player to craft Estrogen thro Create. To get the estrogen you need to be already advanced in create. When you create the estrogen pill it will allow the player to be able to dash for 5 minutes (You need to touch the ground each time to recharge the dash). P.D: Dave would love it

**Comment by Derpius** [comment]
I'm assuming this is a joke so closing, but let me know if there's a proper reason to add this
