### ISSUE TITLE
chatbox replacement

### ISSUE THREAD

**Issue by Zubbbz** [TAServers/issues#6]
because derp is way too fucking picky to choose an existing option (and we need our own custom one if we want discord integration so touche)

**Comment by Zubbbz** [comment]
# TODO:
- [ ] Discord Integration
	- [ ] Differentiate between game chat and discord
- [ ] Resizeable
- [ ] Highly configurable (contribute ideas)

**Comment by Kilometres** [comment]
[Resolved](https://github.com/TAServers/gmod-custom-chat)
